### ISSUE TITLE
Implement an easy way to get the output binaries generated inside the container

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/neosearch#10]
Right now it is not possible to get the binaries that have been built inside the container.

Docker solves this with its _bundles_ directory. The binaries generated inside of it have root as owner, and a directory is created for each different version of the build.

Something like that would be enough ?

**Comment by i4ki** [comment]
Yes. I read the docker build source code and copy/paste/change some useful parts to usage in neosearch. I think that solves our problem, we can continue improving this model from #11. What do you think?
