### ISSUE TITLE
Choose a good dependency management tool

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/neosearch#22]
We have used Godep in the beginning, but I don't know if this is the better option.

**Comment by katcipis** [comment]
Should we go for some vendoring ? :-)

**Comment by i4ki** [comment]
Yeah. But how? =)

What do you think of create a repository for vendoring? I don't like the idea of vendor inside the neosearch repo... Then the import path's will be:

import "github.com/NeowayLabs/go3rdparty/jmhodges/levigo"

bizarre?

**Comment by katcipis** [comment]
I think it is exactly that. Just the name of the vendor directory that Im not sure yet. Is there any pattern that Gophers already enjoy ?

**Comment by i4ki** [comment]
Have you read the discussion below? =P
https://groups.google.com/forum/#!topic/golang-dev/nMWoEAG55v8%5B1-25%5D

**Comment by i4ki** [comment]
About the vendoring directory when inside of the same repository I guess that "internal" is the consensus for such thing. But for outside vendoring I don't know if exist any standard.

**Comment by katcipis** [comment]
There is also this post:

http://nathany.com/go-packages/

Comparing different approaches. I think we could go with the _internal_ approach then :-). I would like more _3rdparty_, the intention is more clear (honestly..._internal_ says absolutely nothing about the purpose of what is inside :P). 

But there is no need to diverge from the community :-)

**Comment by i4ki** [comment]
The community are using tools like godep... Let's use it too and if we have some problem we discuss alternatives in the future. The commit 0b4871e7e2db16b6c9b6a92baa2b1f41b269e46a reintroduces Godeps vendoring directory.
