### ISSUE TITLE
Improve the KVStore interface

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/neosearch#40]
We need to create a KVReader and KVWriter interfaces to do a correct locking strategy.

**Comment by i4ki** [comment]
Fixed by commit 42a229c4ed20486ca52473dcf4a4f0752cc66746

**Comment by ppizarro** [comment]
Trabalhei nisso nesse fim de semana conforme tínhamos combinado :(

Já não temos muito tempo para trabalharmos no projeto. É mau fazermos o
trampo repetido :(
