### ISSUE TITLE
Dev environment

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/neosearch#5]
Build a dev environment. Right now I only know Vagrant and Fig for this (if docker will be the provider).

Any ideas are welcome :-)

**Comment by katcipis** [comment]
I did the initial work on a branch:

https://github.com/NeowayLabs/neosearch/tree/addingDevEnv

It seems pretty easy to change code and just make it :-)

If it is acceptable I can make a pull request.

**Comment by i4ki** [comment]
Branch addingDevEnv merged into master
